// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: process.env.NODE_ENV === "production" ? "tsx prisma/seed.ts" : "tsx prisma/seed-dev.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
